#!/bin/bash

# Check if systemd is fully initialized before proceeding
while ! systemctl is-system-running; do sleep 1; done

# Update package information and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 3.80.64.75:80 check
    server web-02 100.25.213.47:80 check
EOL

# Enable HAProxy as a service managed by init system
sudo tee /etc/default/haproxy > /dev/null <<EOL
ENABLED=1
EOL

# Restart HAProxy service
sudo systemctl restart haproxy
